modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "${mod_icon}"

[[dependencies.fishtastic]]
modId = "forge"
mandatory = true
versionRange = "[47.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fishtastic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fishtastic]]
modId = "gelatinui"
mandatory = false
versionRange = "${mod_gelatinui_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.fishtastic]]
modId = "jei"
mandatory = false
versionRange = "[15.20,)"
ordering = "NONE"
side = "CLIENT"
