package grill24.fishtastic.shapegen;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

/**
 * Shared Minecraft block-model JSON-building helpers used by every part generator
 * (frame/sand/glass) — kept identical to what the original hand-written datagen providers
 * produced, so this extraction is a pure decomposition, not a behavior change.
 */
public final class TankShapeGeometry {
    public static final int PERMUTATION_COUNT = 64;

    private TankShapeGeometry() {}

    public static JsonArray vec3(int x, int y, int z) {
        JsonArray vec = new JsonArray();
        vec.add(x);
        vec.add(y);
        vec.add(z);
        return vec;
    }

    public static JsonObject face(int u1, int v1, int u2, int v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(u1);
        uv.add(v1);
        uv.add(u2);
        uv.add(v2);
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    /**
     * Fractional-coordinate sibling of {@link #vec3(int, int, int)} for geometry that isn't
     * pixel-aligned — components that happen to be whole numbers still serialize as {@code 1},
     * not {@code 1.0}, via {@link #smartNumber}, so a generator can use this unconditionally and
     * still produce byte-identical output to the checked-in models whenever every coordinate
     * happens to land on a whole number (which is always true here: every run/width is derived
     * from integer image-row indices, and the sand floor is a fixed 1px).
     */
    public static JsonArray vec3(double x, double y, double z) {
        JsonArray vec = new JsonArray();
        vec.add(smartNumber(x));
        vec.add(smartNumber(y));
        vec.add(smartNumber(z));
        return vec;
    }

    /** Fractional-coordinate sibling of {@link #face(int, int, int, int, String)} — see its note. */
    public static JsonObject face(double u1, double v1, double u2, double v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(smartNumber(u1));
        uv.add(smartNumber(v1));
        uv.add(smartNumber(u2));
        uv.add(smartNumber(v2));
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    /**
     * Formats a coordinate the same way {@link #vec3(double, double, double)}/{@link #face}
     * serialize it — as a plain integer when whole, a decimal otherwise — for building element
     * {@code name} strings that need to match the original hand-written datagen's naming
     * byte-for-byte wherever the underlying value happens to be a whole number.
     */
    public static String smartLabel(double value) {
        return String.valueOf(smartNumber(value));
    }

    /** Whole-valued doubles serialize as plain integers (matching the original hand-written
     * datagen's output), everything else as a decimal. */
    private static Number smartNumber(double value) {
        if (!Double.isInfinite(value) && !Double.isNaN(value) && value == Math.rint(value)
                && value >= Integer.MIN_VALUE && value <= Integer.MAX_VALUE) {
            return (int) value;
        }
        return value;
    }

    /** The model JSON shell shared by every generated permutation: format_version/credit/parent/textures. */
    public static JsonObject baseModel(String textureId) {
        JsonObject model = new JsonObject();
        model.addProperty("format_version", "1.21.1");
        model.addProperty("credit", "Generated by Fishtastic Data Generator");
        model.addProperty("parent", "block/block");

        JsonObject textures = new JsonObject();
        textures.addProperty("particle", "#all");
        textures.addProperty("all", textureId);
        model.add("textures", textures);

        return model;
    }

    /** Attaches a single-entry "groups" array (Blockbench organization), as the frame/sand models do. */
    public static void addSingleGroup(JsonObject model, String groupName) {
        JsonArray groups = new JsonArray();
        JsonObject baseGroup = new JsonObject();
        baseGroup.addProperty("name", groupName);
        baseGroup.add("origin", vec3(0, 0, 0));
        baseGroup.addProperty("color", 0);
        groups.add(baseGroup);
        model.add("groups", groups);
    }
}
