package grill24.fishtastic.fabric.datagen;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import grill24.fishtastic.Fishtastic;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.core.Direction;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Data generator for fish tank sand models.
 * Generates all 64 permutations of the sand model (2^6 combinations of open/closed faces).
 *
 * Each permutation is identified by an index (0-63) where each bit represents whether a face is open:
 * - Bit 0: DOWN
 * - Bit 1: UP
 * - Bit 2: NORTH
 * - Bit 3: SOUTH
 * - Bit 4: WEST
 * - Bit 5: EAST
 *
 * Sand behavior:
 * - If DOWN is open (bit 0 = 1), no sand is rendered (empty model)
 * - Sand extends to edges in cardinal directions where those faces are open
 * - Base sand dimensions: [1, 1, 1] to [15, 2, 15]
 * - Extensions go to [0, 1, 0/16] in their respective direction
 */
public class FishTankSandModelProvider implements DataProvider {
    private final PackOutput.PathProvider pathProvider;

    public FishTankSandModelProvider(FabricPackOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "models/block");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();

        // Generate all 64 permutations (2^6 for 6 faces)
        for (int i = 0; i < 64; i++) {
            futures.add(generateSandModel(cache, i));
        }

        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    /**
     * Generate a sand model for a specific permutation.
     */
    private CompletableFuture<?> generateSandModel(CachedOutput cache, int permutationIndex) {
        Set<Direction> openFaces = getOpenFaces(permutationIndex);

        JsonObject model = new JsonObject();
        model.addProperty("format_version", "1.21.1");
        model.addProperty("credit", "Generated by Fishtastic Data Generator");
        model.addProperty("parent", "block/block");

        // Textures - define texture slots with defaults that can be overridden
        JsonObject textures = new JsonObject();
        textures.addProperty("particle", "#all");
        textures.addProperty("all", "block/sand");
        model.add("textures", textures);

        // Elements
        JsonArray elements = new JsonArray();

        // If bottom is open, no sand at all (empty model)
        if (!openFaces.contains(Direction.DOWN)) {
            // Add base sand layer
            elements.add(createBaseSand());

            // Add extensions for open sides
            if (openFaces.contains(Direction.NORTH)) {
                elements.add(createNorthExtension());
            }
            if (openFaces.contains(Direction.SOUTH)) {
                elements.add(createSouthExtension());
            }
            if (openFaces.contains(Direction.WEST)) {
                elements.add(createWestExtension());
            }
            if (openFaces.contains(Direction.EAST)) {
                elements.add(createEastExtension());
            }

            // Add corner extensions where both adjacent sides are open
            if (openFaces.contains(Direction.NORTH) && openFaces.contains(Direction.WEST)) {
                elements.add(createCornerExtension(0, 0)); // NW
            }
            if (openFaces.contains(Direction.NORTH) && openFaces.contains(Direction.EAST)) {
                elements.add(createCornerExtension(15, 0)); // NE
            }
            if (openFaces.contains(Direction.SOUTH) && openFaces.contains(Direction.WEST)) {
                elements.add(createCornerExtension(0, 15)); // SW
            }
            if (openFaces.contains(Direction.SOUTH) && openFaces.contains(Direction.EAST)) {
                elements.add(createCornerExtension(15, 15)); // SE
            }
        }

        model.add("elements", elements);

        // Groups (for organization in Blockbench)
        JsonArray groups = new JsonArray();
        JsonObject baseGroup = new JsonObject();
        baseGroup.addProperty("name", "sand_" + permutationIndex);
        baseGroup.add("origin", createVec3(0, 0, 0));
        baseGroup.addProperty("color", 0);
        groups.add(baseGroup);
        model.add("groups", groups);

        Path path = pathProvider.json(Fishtastic.id("fishtankbase/fish_tank_sand_" + permutationIndex));
        return DataProvider.saveStable(cache, model, path);
    }

    /**
     * Get the set of open faces from a permutation index.
     */
    private Set<Direction> getOpenFaces(int index) {
        Set<Direction> openFaces = java.util.EnumSet.noneOf(Direction.class);
        for (Direction dir : Direction.values()) {
            if ((index & (1 << dir.ordinal())) != 0) {
                openFaces.add(dir);
            }
        }
        return openFaces;
    }

    // ========== Element Creation Methods ==========

    /**
     * Create the base sand layer (center area between frame edges).
     * Dimensions: [1, 1, 1] to [15, 2, 15]
     */
    private JsonObject createBaseSand() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "base_sand");
        element.add("from", createVec3(1, 1, 1));
        element.add("to", createVec3(15, 2, 15));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(1, 14, 15, 15, "#all"));
        faces.add("east", createFace(1, 14, 15, 15, "#all"));
        faces.add("south", createFace(1, 14, 15, 15, "#all"));
        faces.add("west", createFace(1, 14, 15, 15, "#all"));
        faces.add("up", createFace(1, 1, 15, 15, "#all"));
        faces.add("down", createFace(1, 1, 15, 15, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create north extension - extends from base to north edge.
     * Dimensions: [1, 1, 0] to [15, 2, 1]
     */
    private JsonObject createNorthExtension() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "north_extension");
        element.add("from", createVec3(1, 1, 0));
        element.add("to", createVec3(15, 2, 1));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(1, 14, 15, 15, "#all"));
        faces.add("east", createFace(0, 14, 1, 15, "#all"));
        faces.add("south", createFace(1, 14, 15, 15, "#all"));
        faces.add("west", createFace(0, 14, 1, 15, "#all"));
        faces.add("up", createFace(1, 0, 15, 1, "#all"));
        faces.add("down", createFace(1, 0, 15, 1, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create south extension - extends from base to south edge.
     * Dimensions: [1, 1, 15] to [15, 2, 16]
     */
    private JsonObject createSouthExtension() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "south_extension");
        element.add("from", createVec3(1, 1, 15));
        element.add("to", createVec3(15, 2, 16));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(1, 14, 15, 15, "#all"));
        faces.add("east", createFace(15, 14, 16, 15, "#all"));
        faces.add("south", createFace(1, 14, 15, 15, "#all"));
        faces.add("west", createFace(15, 14, 16, 15, "#all"));
        faces.add("up", createFace(1, 15, 15, 16, "#all"));
        faces.add("down", createFace(1, 15, 15, 16, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create west extension - extends from base to west edge.
     * Dimensions: [0, 1, 1] to [1, 2, 15]
     */
    private JsonObject createWestExtension() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "west_extension");
        element.add("from", createVec3(0, 1, 1));
        element.add("to", createVec3(1, 2, 15));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(0, 14, 1, 15, "#all"));
        faces.add("east", createFace(1, 14, 15, 15, "#all"));
        faces.add("south", createFace(0, 14, 1, 15, "#all"));
        faces.add("west", createFace(1, 14, 15, 15, "#all"));
        faces.add("up", createFace(0, 1, 1, 15, "#all"));
        faces.add("down", createFace(0, 1, 1, 15, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create east extension - extends from base to east edge.
     * Dimensions: [15, 1, 1] to [16, 2, 15]
     */
    private JsonObject createEastExtension() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "east_extension");
        element.add("from", createVec3(15, 1, 1));
        element.add("to", createVec3(16, 2, 15));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(15, 14, 16, 15, "#all"));
        faces.add("east", createFace(1, 14, 15, 15, "#all"));
        faces.add("south", createFace(15, 14, 16, 15, "#all"));
        faces.add("west", createFace(1, 14, 15, 15, "#all"));
        faces.add("up", createFace(15, 1, 16, 15, "#all"));
        faces.add("down", createFace(15, 1, 16, 15, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create corner extension - fills corner when both adjacent sides are open.
     * x, z are either 0 or 15 depending on which corner.
     */
    private JsonObject createCornerExtension(int x, int z) {
        JsonObject element = new JsonObject();
        element.addProperty("name", "corner_extension_" + x + "_" + z);
        element.add("from", createVec3(x, 1, z));
        element.add("to", createVec3(x + 1, 2, z + 1));

        JsonObject faces = new JsonObject();
        // All corner faces use the same texture
        faces.add("north", createFace(x, 14, x + 1, 15, "#all"));
        faces.add("east", createFace(z, 14, z + 1, 15, "#all"));
        faces.add("south", createFace(x, 14, x + 1, 15, "#all"));
        faces.add("west", createFace(z, 14, z + 1, 15, "#all"));
        faces.add("up", createFace(x, z, x + 1, z + 1, "#all"));
        faces.add("down", createFace(x, z, x + 1, z + 1, "#all"));
        element.add("faces", faces);

        return element;
    }

    // ========== Helper Methods ==========

    private JsonArray createVec3(int x, int y, int z) {
        JsonArray vec = new JsonArray();
        vec.add(x);
        vec.add(y);
        vec.add(z);
        return vec;
    }

    private JsonObject createFace(int u1, int v1, int u2, int v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(u1);
        uv.add(v1);
        uv.add(u2);
        uv.add(v2);
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    @Override
    public String getName() {
        return "Fish Tank Sand Models";
    }
}

