package grill24.fishtastic.fabric.datagen;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import grill24.fishtastic.Fishtastic;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.core.Direction;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Data generator for fish tank frame models.
 * Generates all 64 permutations of the frame model (2^6 combinations of open/closed faces).
 *
 * Each permutation is identified by an index (0-63) where each bit represents whether a face is open:
 * - Bit 0: DOWN
 * - Bit 1: UP
 * - Bit 2: NORTH
 * - Bit 3: SOUTH
 * - Bit 4: WEST
 * - Bit 5: EAST
 */
public class FishTankFrameModelProvider implements DataProvider {
    private final PackOutput.PathProvider pathProvider;

    public FishTankFrameModelProvider(FabricDataOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "models/block");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();

        // Generate all 64 permutations (2^6 for 6 faces)
        for (int i = 0; i < 64; i++) {
            futures.add(generateFrameModel(cache, i));
        }

        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    /**
     * Generate a frame model for a specific permutation.
     */
    private CompletableFuture<?> generateFrameModel(CachedOutput cache, int permutationIndex) {
        Set<Direction> openFaces = getOpenFaces(permutationIndex);

        JsonObject model = new JsonObject();
        model.addProperty("format_version", "1.21.1");
        model.addProperty("credit", "Generated by Fishtastic Data Generator");
        model.addProperty("parent", "block/block");

        // Textures - define texture slots with defaults that can be overridden
        JsonObject textures = new JsonObject();
        textures.addProperty("particle", "#glass");
        textures.addProperty("frame", "block/oak_planks");
        textures.addProperty("glass", "block/blue_stained_glass");
        model.add("textures", textures);

        // Elements
        JsonArray elements = new JsonArray();

        // Add ceiling if UP face is closed
        if (!openFaces.contains(Direction.UP)) {
            elements.add(createCeiling());
        }

        // Add floor if DOWN face is closed
        if (!openFaces.contains(Direction.DOWN)) {
            elements.add(createFloor());
        }

        // Add corner supports only if BOTH adjacent edges are closed
        // If either edge is open, that edge will extend to cover the corner instead
        if (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.WEST)) {
            elements.add(createSupport(0, 0, openFaces));      // NW corner
        }
        if (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.EAST)) {
            elements.add(createSupport(15, 0, openFaces));     // NE corner
        }
        if (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.WEST)) {
            elements.add(createSupport(0, 15, openFaces));     // SW corner
        }
        if (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.EAST)) {
            elements.add(createSupport(15, 15, openFaces));    // SE corner
        }

        // Add edge frames for closed faces, extended to cover corners where adjacent edge is open
        if (!openFaces.contains(Direction.NORTH)) {
            elements.add(createNorthEdge(openFaces));
        }
        if (!openFaces.contains(Direction.SOUTH)) {
            elements.add(createSouthEdge(openFaces));
        }
        if (!openFaces.contains(Direction.WEST)) {
            elements.add(createWestEdge(openFaces));
        }
        if (!openFaces.contains(Direction.EAST)) {
            elements.add(createEastEdge(openFaces));
        }

        model.add("elements", elements);

        // Groups (for organization in Blockbench)
        JsonArray groups = new JsonArray();
        JsonObject baseGroup = new JsonObject();
        baseGroup.addProperty("name", "frame_" + permutationIndex);
        baseGroup.add("origin", createVec3(0, 0, 0));
        baseGroup.addProperty("color", 0);
        groups.add(baseGroup);
        model.add("groups", groups);

        Path path = pathProvider.json(Fishtastic.id("fish_tank_frame_" + permutationIndex));
        return DataProvider.saveStable(cache, model, path);
    }

    /**
     * Get the set of open faces from a permutation index.
     */
    private Set<Direction> getOpenFaces(int index) {
        Set<Direction> openFaces = java.util.EnumSet.noneOf(Direction.class);
        for (Direction dir : Direction.values()) {
            if ((index & (1 << dir.ordinal())) != 0) {
                openFaces.add(dir);
            }
        }
        return openFaces;
    }

    // ========== Element Creation Methods ==========

    private JsonObject createCeiling() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "ceiling");
        element.add("from", createVec3(0, 15, 0));
        element.add("to", createVec3(16, 16, 16));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(0, 0, 16, 1, "#frame"));
        faces.add("east", createFace(0, 0, 16, 1, "#frame"));
        faces.add("south", createFace(0, 0, 16, 1, "#frame"));
        faces.add("west", createFace(0, 0, 16, 1, "#frame"));
        faces.add("up", createFace(0, 0, 16, 16, "#frame"));
        faces.add("down", createFace(0, 0, 16, 16, "#frame"));
        element.add("faces", faces);

        return element;
    }

    private JsonObject createFloor() {
        JsonObject element = new JsonObject();
        element.addProperty("name", "floor");
        element.add("from", createVec3(0, 0, 0));
        element.add("to", createVec3(16, 1, 16));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(0, 0, 16, 1, "#frame"));
        faces.add("east", createFace(0, 0, 16, 1, "#frame"));
        faces.add("south", createFace(0, 0, 16, 1, "#frame"));
        faces.add("west", createFace(0, 0, 16, 1, "#frame"));
        faces.add("up", createFace(0, 0, 16, 16, "#frame"));
        faces.add("down", createFace(0, 0, 16, 16, "#frame"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create a corner support pillar.
     * Height is adjusted based on whether floor/ceiling are present.
     * Each face uses glass texture if the adjacent edge is open, frame texture otherwise.
     */
    private JsonObject createSupport(int x, int z, Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "support_" + x + "_" + z);
        element.add("from", createVec3(x, minY, z));
        element.add("to", createVec3(x + 1, maxY, z + 1));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;

        // Each face uses glass if the adjacent edge is open, frame otherwise. Using x,z direction, set for all tex uvs.
        // convert x and z to directions
        Direction northDir = (z == 0) ? Direction.NORTH : Direction.SOUTH;
        Direction westDir = (x == 0) ? Direction.WEST : Direction.EAST;

        String tex = "#frame";
        if(openFaces.contains(northDir) || openFaces.contains(westDir)) {
            tex = "#glass";
        }

        faces.add("north", createFace(0, 0, 1, heightUV, tex));
        faces.add("east", createFace(0, 0, 1, heightUV, tex));
        faces.add("south", createFace(0, 0, 1, heightUV, tex));
        faces.add("west", createFace(0, 0, 1, heightUV, tex));
        faces.add("up", createFace(0, 0, 1, 1, tex));
        faces.add("down", createFace(0, 0, 1, 1, tex));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create horizontal edge frame for the north face (between corners).
     * Extends to corners if adjacent perpendicular edges are open.
     */
    private JsonObject createNorthEdge(Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        // Extend to cover corners if perpendicular edges are open
        int minX = openFaces.contains(Direction.WEST) ? 0 : 1;
        int maxX = openFaces.contains(Direction.EAST) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "edge_north");
        element.add("from", createVec3(minX, minY, 0));
        element.add("to", createVec3(maxX, maxY, 1));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;
        faces.add("north", createFace(minX, 0, maxX, heightUV, "#glass"));
        faces.add("east", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("south", createFace(minX, 0, maxX, heightUV, "#glass"));
        faces.add("west", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("up", createFace(minX, 0, maxX, 1, "#glass"));
        faces.add("down", createFace(minX, 0, maxX, 1, "#glass"));
        element.add("faces", faces);

        return element;
    }

    private JsonObject createSouthEdge(Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        // Extend to cover corners if perpendicular edges are open
        int minX = openFaces.contains(Direction.WEST) ? 0 : 1;
        int maxX = openFaces.contains(Direction.EAST) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "edge_south");
        element.add("from", createVec3(minX, minY, 15));
        element.add("to", createVec3(maxX, maxY, 16));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;
        faces.add("north", createFace(minX, 0, maxX, heightUV, "#glass"));
        faces.add("east", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("south", createFace(minX, 0, maxX, heightUV, "#glass"));
        faces.add("west", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("up", createFace(minX, 0, maxX, 1, "#glass"));
        faces.add("down", createFace(minX, 0, maxX, 1, "#glass"));
        element.add("faces", faces);

        return element;
    }

    private JsonObject createWestEdge(Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        // Extend to cover corners if perpendicular edges are open
        int minZ = openFaces.contains(Direction.NORTH) ? 0 : 1;
        int maxZ = openFaces.contains(Direction.SOUTH) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "edge_west");
        element.add("from", createVec3(0, minY, minZ));
        element.add("to", createVec3(1, maxY, maxZ));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;
        faces.add("north", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("east", createFace(minZ, 0, maxZ, heightUV, "#glass"));
        faces.add("south", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("west", createFace(minZ, 0, maxZ, heightUV, "#glass"));
        faces.add("up", createFace(0, minZ, 1, maxZ, "#glass"));
        faces.add("down", createFace(0, minZ, 1, maxZ, "#glass"));
        element.add("faces", faces);

        return element;
    }

    private JsonObject createEastEdge(Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        // Extend to cover corners if perpendicular edges are open
        int minZ = openFaces.contains(Direction.NORTH) ? 0 : 1;
        int maxZ = openFaces.contains(Direction.SOUTH) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "edge_east");
        element.add("from", createVec3(15, minY, minZ));
        element.add("to", createVec3(16, maxY, maxZ));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;
        faces.add("north", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("east", createFace(minZ, 0, maxZ, heightUV, "#glass"));
        faces.add("south", createFace(0, 0, 1, heightUV, "#glass"));
        faces.add("west", createFace(minZ, 0, maxZ, heightUV, "#glass"));
        faces.add("up", createFace(0, minZ, 1, maxZ, "#glass"));
        faces.add("down", createFace(0, minZ, 1, maxZ, "#glass"));
        element.add("faces", faces);

        return element;
    }

    // ========== Helper Methods ==========

    private JsonArray createVec3(int x, int y, int z) {
        JsonArray vec = new JsonArray();
        vec.add(x);
        vec.add(y);
        vec.add(z);
        return vec;
    }

    private JsonObject createFace(int u1, int v1, int u2, int v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(u1);
        uv.add(v1);
        uv.add(u2);
        uv.add(v2);
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    @Override
    public String getName() {
        return "Fish Tank Frame Models";
    }
}

