package grill24.fishtastic.fabric.datagen;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import grill24.fishtastic.Fishtastic;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.core.Direction;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Data generator for fish tank glass models.
 * Generates all 64 permutations of the glass model (2^6 combinations of open/closed faces).
 *
 * Each permutation is identified by an index (0-63) where each bit represents whether a face is open:
 * - Bit 0: DOWN
 * - Bit 1: UP
 * - Bit 2: NORTH
 * - Bit 3: SOUTH
 * - Bit 4: WEST
 * - Bit 5: EAST
 */
public class FishTankGlassModelProvider implements DataProvider {
    private final PackOutput.PathProvider pathProvider;

    public FishTankGlassModelProvider(FabricPackOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "models/block");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();

        // Generate all 64 permutations (2^6 for 6 faces)
        for (int i = 0; i < 64; i++) {
            futures.add(generateGlassModel(cache, i));
        }

        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    /**
     * Generate a glass model for a specific permutation.
     */
    private CompletableFuture<?> generateGlassModel(CachedOutput cache, int permutationIndex) {
        Set<Direction> openFaces = getOpenFaces(permutationIndex);

        JsonObject model = new JsonObject();
        model.addProperty("format_version", "1.21.1");
        model.addProperty("credit", "Generated by Fishtastic Data Generator");
        model.addProperty("parent", "block/block");

        // Textures - only glass texture needed
        JsonObject textures = new JsonObject();
        textures.addProperty("particle", "#all");
        textures.addProperty("all", "block/blue_stained_glass");
        model.add("textures", textures);

        // Elements - only glass panes
        JsonArray elements = new JsonArray();

        // Add glass panes for each CLOSED face (open faces have no glass)
        // Glass panes are thin (1 pixel thick) and placed on the outer edge
        // They are shortened to avoid overlapping with corner supports
        if (!openFaces.contains(Direction.NORTH)) {
            elements.add(createNorthGlassPane(openFaces));
        }
        if (!openFaces.contains(Direction.SOUTH)) {
            elements.add(createSouthGlassPane(openFaces));
        }
        if (!openFaces.contains(Direction.WEST)) {
            elements.add(createWestGlassPane(openFaces));
        }
        if (!openFaces.contains(Direction.EAST)) {
            elements.add(createEastGlassPane(openFaces));
        }

        model.add("elements", elements);

        // Save the model file
        Path outputPath = pathProvider.json(Identifier.fromNamespaceAndPath(Fishtastic.MOD_ID, "fishtankbase/fish_tank_glass_" + permutationIndex));
        return DataProvider.saveStable(cache, model, outputPath);
    }

    /**
     * Create a glass pane for the north face (Z=0).
     * Glass panes are 1 pixel thick and shortened to avoid corner supports.
     * Extends vertically when UP or DOWN faces are open (connected to another tank).
     */
    private JsonObject createNorthGlassPane(Set<Direction> openFaces) {
        // Determine if we need to shorten the glass to avoid corner supports
        // NW corner support exists if both NORTH and WEST are closed
        // NE corner support exists if both NORTH and EAST are closed
        int minX = (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.WEST)) ? 1 : 0;
        int maxX = (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.EAST)) ? 15 : 16;

        // Extend vertically when UP or DOWN faces are open (connected to another tank)
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.add("from", createVec3(minX, minY, 0));
        element.add("to", createVec3(maxX, maxY, 1));

        JsonObject faces = new JsonObject();
        // Only render the two large outward-facing sides
        faces.add("north", createFace(minX, minY, maxX, maxY, "#all"));
        faces.add("south", createFace(minX, minY, maxX, maxY, "#all"));

        element.add("faces", faces);
        return element;
    }

    /**
     * Create a glass pane for the south face (Z=16).
     * Shortened to avoid corner supports where needed.
     * Extends vertically when UP or DOWN faces are open.
     */
    private JsonObject createSouthGlassPane(Set<Direction> openFaces) {
        // SW corner support exists if both SOUTH and WEST are closed
        // SE corner support exists if both SOUTH and EAST are closed
        int minX = (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.WEST)) ? 1 : 0;
        int maxX = (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.EAST)) ? 15 : 16;

        // Extend vertically when UP or DOWN faces are open
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.add("from", createVec3(minX, minY, 15));
        element.add("to", createVec3(maxX, maxY, 16));

        JsonObject faces = new JsonObject();
        faces.add("north", createFace(minX, minY, maxX, maxY, "#all"));
        faces.add("south", createFace(minX, minY, maxX, maxY, "#all"));

        element.add("faces", faces);
        return element;
    }

    /**
     * Create a glass pane for the west face (X=0).
     * Shortened to avoid corner supports where needed.
     * Extends vertically when UP or DOWN faces are open.
     */
    private JsonObject createWestGlassPane(Set<Direction> openFaces) {
        // NW corner support exists if both NORTH and WEST are closed
        // SW corner support exists if both SOUTH and WEST are closed
        int minZ = (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.WEST)) ? 1 : 0;
        int maxZ = (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.WEST)) ? 15 : 16;

        // Extend vertically when UP or DOWN faces are open
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.add("from", createVec3(0, minY, minZ));
        element.add("to", createVec3(1, maxY, maxZ));

        JsonObject faces = new JsonObject();
        faces.add("west", createFace(minZ, minY, maxZ, maxY, "#all"));
        faces.add("east", createFace(minZ, minY, maxZ, maxY, "#all"));

        element.add("faces", faces);
        return element;
    }

    /**
     * Create a glass pane for the east face (X=16).
     * Shortened to avoid corner supports where needed.
     * Extends vertically when UP or DOWN faces are open.
     */
    private JsonObject createEastGlassPane(Set<Direction> openFaces) {
        // NE corner support exists if both NORTH and EAST are closed
        // SE corner support exists if both SOUTH and EAST are closed
        int minZ = (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.EAST)) ? 1 : 0;
        int maxZ = (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.EAST)) ? 15 : 16;

        // Extend vertically when UP or DOWN faces are open
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.add("from", createVec3(15, minY, minZ));
        element.add("to", createVec3(16, maxY, maxZ));

        JsonObject faces = new JsonObject();
        faces.add("west", createFace(minZ, minY, maxZ, maxY, "#all"));
        faces.add("east", createFace(minZ, minY, maxZ, maxY, "#all"));

        element.add("faces", faces);
        return element;
    }

    /**
     * Get the set of open faces for a permutation index.
     */
    private Set<Direction> getOpenFaces(int permutationIndex) {
        Set<Direction> openFaces = java.util.EnumSet.noneOf(Direction.class);
        if ((permutationIndex & 1) != 0) openFaces.add(Direction.DOWN);
        if ((permutationIndex & 2) != 0) openFaces.add(Direction.UP);
        if ((permutationIndex & 4) != 0) openFaces.add(Direction.NORTH);
        if ((permutationIndex & 8) != 0) openFaces.add(Direction.SOUTH);
        if ((permutationIndex & 16) != 0) openFaces.add(Direction.WEST);
        if ((permutationIndex & 32) != 0) openFaces.add(Direction.EAST);
        return openFaces;
    }

    private JsonArray createVec3(int x, int y, int z) {
        JsonArray vec = new JsonArray();
        vec.add(x);
        vec.add(y);
        vec.add(z);
        return vec;
    }

    private JsonObject createFace(int u1, int v1, int u2, int v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(u1);
        uv.add(v1);
        uv.add(u2);
        uv.add(v2);
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    @Override
    public String getName() {
        return "Fish Tank Glass Models";
    }
}
