package grill24.fishtastic.fabric.datagen;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import grill24.fishtastic.Fishtastic;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.core.Direction;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Data generator for fish tank frame models.
 * Generates all 64 permutations of the frame model (2^6 combinations of open/closed faces).
 *
 * Each permutation is identified by an index (0-63) where each bit represents whether a face is open:
 * - Bit 0: DOWN
 * - Bit 1: UP
 * - Bit 2: NORTH
 * - Bit 3: SOUTH
 * - Bit 4: WEST
 * - Bit 5: EAST
 */
public class FishTankFrameModelProvider implements DataProvider {
    private final PackOutput.PathProvider pathProvider;

    public FishTankFrameModelProvider(FabricPackOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "models/block");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();

        // Generate all 64 permutations (2^6 for 6 faces)
        for (int i = 0; i < 64; i++) {
            futures.add(generateFrameModel(cache, i));
        }

        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    /**
     * Generate a frame model for a specific permutation.
     */
    private CompletableFuture<?> generateFrameModel(CachedOutput cache, int permutationIndex) {
        Set<Direction> openFaces = getOpenFaces(permutationIndex);

        JsonObject model = new JsonObject();
        model.addProperty("format_version", "1.21.1");
        model.addProperty("credit", "Generated by Fishtastic Data Generator");
        model.addProperty("parent", "block/block");

        // Textures - only frame texture needed (glass is separate now)
        JsonObject textures = new JsonObject();
        textures.addProperty("particle", "#all");
        textures.addProperty("all", "block/oak_planks");
        model.add("textures", textures);

        // Elements
        JsonArray elements = new JsonArray();

        // Add ceiling if UP face is closed
        if (!openFaces.contains(Direction.UP)) {
            elements.add(createCeiling(openFaces));
        }

        // Add floor if DOWN face is closed
        if (!openFaces.contains(Direction.DOWN)) {
            elements.add(createFloor(openFaces));
        }

        // Add corner supports only if BOTH adjacent edges are closed
        // If either edge is open, that edge will extend to cover the corner instead
        if (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.WEST)) {
            elements.add(createSupport(0, 0, openFaces));      // NW corner
        }
        if (!openFaces.contains(Direction.NORTH) && !openFaces.contains(Direction.EAST)) {
            elements.add(createSupport(15, 0, openFaces));     // NE corner
        }
        if (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.WEST)) {
            elements.add(createSupport(0, 15, openFaces));     // SW corner
        }
        if (!openFaces.contains(Direction.SOUTH) && !openFaces.contains(Direction.EAST)) {
            elements.add(createSupport(15, 15, openFaces));    // SE corner
        }

        model.add("elements", elements);

        // Groups (for organization in Blockbench)
        JsonArray groups = new JsonArray();
        JsonObject baseGroup = new JsonObject();
        baseGroup.addProperty("name", "frame_" + permutationIndex);
        baseGroup.add("origin", createVec3(0, 0, 0));
        baseGroup.addProperty("color", 0);
        groups.add(baseGroup);
        model.add("groups", groups);

        Path path = pathProvider.json(Fishtastic.id("fishtankbase/fish_tank_frame_" + permutationIndex));
        return DataProvider.saveStable(cache, model, path);
    }

    /**
     * Get the set of open faces from a permutation index.
     */
    private Set<Direction> getOpenFaces(int index) {
        Set<Direction> openFaces = java.util.EnumSet.noneOf(Direction.class);
        for (Direction dir : Direction.values()) {
            if ((index & (1 << dir.ordinal())) != 0) {
                openFaces.add(dir);
            }
        }
        return openFaces;
    }

    // ========== Element Creation Methods ==========

    private JsonObject createCeiling(Set<Direction> openFaces) {
        JsonObject element = new JsonObject();
        element.addProperty("name", "ceiling");
        element.add("from", createVec3(0, 15, 0));
        element.add("to", createVec3(16, 16, 16));

        JsonObject faces = new JsonObject();
        // Side lips are only needed where there's no neighboring tank to connect to;
        // otherwise they'd render as a visible seam at the shared boundary.
        if (!openFaces.contains(Direction.NORTH)) faces.add("north", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.EAST)) faces.add("east", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.SOUTH)) faces.add("south", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.WEST)) faces.add("west", createFace(0, 0, 16, 1, "#all"));
        faces.add("up", createFace(0, 0, 16, 16, "#all"));
        faces.add("down", createFace(0, 0, 16, 16, "#all"));
        element.add("faces", faces);

        return element;
    }

    private JsonObject createFloor(Set<Direction> openFaces) {
        JsonObject element = new JsonObject();
        element.addProperty("name", "floor");
        element.add("from", createVec3(0, 0, 0));
        element.add("to", createVec3(16, 1, 16));

        JsonObject faces = new JsonObject();
        // Side lips are only needed where there's no neighboring tank to connect to;
        // otherwise they'd render as a visible seam at the shared boundary.
        if (!openFaces.contains(Direction.NORTH)) faces.add("north", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.EAST)) faces.add("east", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.SOUTH)) faces.add("south", createFace(0, 0, 16, 1, "#all"));
        if (!openFaces.contains(Direction.WEST)) faces.add("west", createFace(0, 0, 16, 1, "#all"));
        faces.add("up", createFace(0, 0, 16, 16, "#all"));
        faces.add("down", createFace(0, 0, 16, 16, "#all"));
        element.add("faces", faces);

        return element;
    }

    /**
     * Create a corner support pillar.
     * Height is adjusted based on whether floor/ceiling are present.
     * Renders all faces since supports only appear when adjacent faces are closed (no conflict with glass).
     */
    private JsonObject createSupport(int x, int z, Set<Direction> openFaces) {
        int minY = openFaces.contains(Direction.DOWN) ? 0 : 1;
        int maxY = openFaces.contains(Direction.UP) ? 16 : 15;

        JsonObject element = new JsonObject();
        element.addProperty("name", "support_" + x + "_" + z);
        element.add("from", createVec3(x, minY, z));
        element.add("to", createVec3(x + 1, maxY, z + 1));

        JsonObject faces = new JsonObject();
        int heightUV = maxY - minY;

        // Render all faces - these supports only exist when both adjacent faces are closed,
        // so they won't conflict with glass (glass appears on closed faces)
        faces.add("north", createFace(0, 0, 1, heightUV, "#all"));
        faces.add("south", createFace(0, 0, 1, heightUV, "#all"));
        faces.add("west", createFace(0, 0, 1, heightUV, "#all"));
        faces.add("east", createFace(0, 0, 1, heightUV, "#all"));
        faces.add("up", createFace(0, 0, 1, 1, "#all"));
        faces.add("down", createFace(0, 0, 1, 1, "#all"));

        element.add("faces", faces);

        return element;
    }

    // ========== Helper Methods ==========

    private JsonArray createVec3(int x, int y, int z) {
        JsonArray vec = new JsonArray();
        vec.add(x);
        vec.add(y);
        vec.add(z);
        return vec;
    }

    private JsonObject createFace(int u1, int v1, int u2, int v2, String texture) {
        JsonObject face = new JsonObject();
        JsonArray uv = new JsonArray();
        uv.add(u1);
        uv.add(v1);
        uv.add(u2);
        uv.add(v2);
        face.add("uv", uv);
        face.addProperty("texture", texture);
        return face;
    }

    @Override
    public String getName() {
        return "Fish Tank Frame Models";
    }
}

