plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.graphics']
}

application {
    mainClass = 'grill24.fishtastic.shapepreviewer.TankShapePreviewerApp'
}

dependencies {
    implementation project(':tools:tank-shape-gen')
}
