"""Copy Fabric-datagen'd custom-registry JSON into common/src/main/resources.

Fabric's FabricPackOutput writes datapack-registry entries (cosmetic_structure,
fish_profile, quest, shop_entry, temperament, item_effect, ...) to
fabric/src/main/generated/data/fishtastic/<registry>/*.json, but the runtime
datapack loader for these mod-namespaced registries resolves them from
common/src/main/resources/data/fishtastic/fishtastic/<registry>/*.json (the
extra "fishtastic" segment is the registry key's own namespace). That folder
is hand-authored source, not build output, so files generated by datagen must
be copied over manually. Run this after `run_datagen.bat` any time a
datapack-registry provider (e.g. CosmeticStructureProvider) changes.
"""
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_ROOT = REPO_ROOT / "fabric" / "src" / "main" / "generated" / "data" / "fishtastic"
DEST_ROOT = REPO_ROOT / "common" / "src" / "main" / "resources" / "data" / "fishtastic" / "fishtastic"

# Registry folder names generated under data/fishtastic/<name>/ that need the
# extra common/.../data/fishtastic/fishtastic/<name>/ nesting at their destination.
#
# Only list registries here whose Fabric datagen provider is the actual source
# of truth for every field in the schema. item_effect, for example, has a
# datagen provider that only emits a subset of ItemEffect's fields (missing
# outline_color/outline_width/outline_falloff/...) while the checked-in JSON
# is hand-tuned with the full set — syncing it would silently drop data.
REGISTRY_DIRS = [
    "cosmetic_structure",
]


def sync_registry(name: str) -> int:
    src = GENERATED_ROOT / name
    dst = DEST_ROOT / name
    if not src.is_dir():
        return 0

    dst.mkdir(parents=True, exist_ok=True)

    src_files = {p.name for p in src.glob("*.json")}
    if not src_files:
        return 0

    # Remove stale destination files that no longer have a generated source,
    # so renamed/removed entries don't leave orphaned JSON behind.
    for existing in dst.glob("*.json"):
        if existing.name not in src_files:
            existing.unlink()
            print(f"  removed stale {existing.relative_to(REPO_ROOT)}")

    for filename in sorted(src_files):
        shutil.copyfile(src / filename, dst / filename)

    return len(src_files)


def main() -> None:
    if not GENERATED_ROOT.is_dir():
        raise SystemExit(
            f"No generated output found at {GENERATED_ROOT}. Run scripts/run_datagen.bat first."
        )

    total = 0
    for registry in REGISTRY_DIRS:
        count = sync_registry(registry)
        if count:
            print(f"{registry}: copied {count} file(s) -> {DEST_ROOT / registry}")
            total += count

    print(f"Done. {total} file(s) synced to {DEST_ROOT}")


if __name__ == "__main__":
    main()
